AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Mercado Pago - Lambda atualiza Cliente
Parameters:
  Environment:
    Description: Tipo do ambiente
    Type: String
  BaseUrlMercadoPago:
    Description: Url Base do mercado pago
    Type: String
  SecretMercadoPagoPath:
    Description: Caminho do secret do mercado pago
    Type: String
  SecretMercadoPagoUseEncryption:
    Description: Secret do mercado pago usa encryption?
    Type: String
  NomeFilaSqs:
    Description: Nome Fila SQS
    Type: String

Resources:  
  MercadoPagoLambdaAtualizarClienteFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: cria um cliente no mercado pago
      FunctionName: !Join ["_", [!Ref Environment, "escoladesoftware-mercadopago-lambdaAtualizarclientefn"]]
      Handler: app.lambdaHandler
      CodeUri: src/
      Runtime: nodejs18.x
      Timeout: 3
      Policies:
        - AmazonSSMReadOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          BaseUrlMercadoPago: !Ref BaseUrlMercadoPago
          SecretMercadoPagoUseEncryption: !Ref SecretMercadoPagoUseEncryption
          SecretMercadoPagoPath: !Ref SecretMercadoPagoPath
    Tags: 
      - Key: Ambiente
        Value: !Ref Environment
      - Key: Microservico
        Value: MercadoPago
      - Key: Servico
        Value: Lambda

  MercadoPagoLambdaAtualizarClienteFnLogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref Environment, "_escoladesoftware-mercadopago-lambdaatualizarclientefn"]]
      RetentionInDays: 3
      Tags: 
        - Key: Ambiente
          Value: !Ref Environment
        - Key: Microservico
          Value: MercadoPago
        - Key: Servico
          Value: LogGroup

  LambdaAtualizarClienteEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${NomeFilaSqs}"
      FunctionName: !GetAtt MercadoPagoLambdaAtualizarClienteFn.Arn
